export const ADD_MESSAGE = "ADD_MESSAGE";
export const RESET_MESSAGE = "RESET_MESSAGE";
export const HISTORY_MESSAGE = "HISTORY_MESSAGE";
export const SOCKET_CONNECTION = "SOCKET_CONNECTION";
export const HISTORY_MESSAGE_APPEND= "HISTORY_MESSAGE_APPEND";
export const ACTIVE_CHANNELID= "ACTIVE_CHANNELID";
export const RESET_CHANNELID= "RESET_CHANNELID";
export const GET_CHATLIST= "GET_CHATLIST";
export const RESET_CHATLIST= "RESET_CHATLIST";
export const CURRENT_ROUTE= "CURRENT_ROUTE";

